#!/bin/sh
kill "$(cat "$HOME"/.cache/pidofbar)"
autostart="dunst mpd mpdsd picom pipewire sbar unclutter"
for program in $autostart; do
    pidof -sx $program >/dev/null || $program &
done
csum=""
new_csum=$(sha1sum "$(which dwm)")
while true
do
    if [ "$csum" != "$new_csum" ]
    then
        csum=$new_csum
        dwm
    else
        exit 0
    fi
    new_csum=$(sha1sum "$(which dwm)")
    sleep 0.5
done
